### PR TITLE
Fix encoding of chains of groups of exceptions

### PR DESCRIPTION
**Pull request by denismerigoux**
Needed by #287, finishes to implement #170.

### CODE REVIEW

**Comment by AltGr** [comment]
This looks good ! If it doesn't take too long I'd prefer to wait for #272 to be merged first (then I can take care of rebasing this) ; it'll probably be easier than handling the conflicts the other way around.

**Review by AltGr — APPROVED** [review]

**Comment by denismerigoux** [comment]
Ok let's wait for #272 to be merged. I tested the rebasing on #287 and it correctly solves my problem :)

**Comment by denismerigoux** [comment]
Can I kindly ask you @AltGr to do the pre-merge or rebase with `master` ?

**Comment by AltGr** [comment]
Rebased!

**Pull request merged**
