### PR TITLE
Use `dates_calc` library

### PR DESCRIPTION
**Pull request by rmonat**
This is a WIP. Current version 0.0.2 of `dates_calc` is in the process of being published, so I guess the CI should fail currently.

- [x] Test current implementation
- [x] I commented out the `duration / duration` operator, can we remove it?
- [x] Need to add support for first and last day of month
- [x] Finish porting the Z3 backend to dates_calc

### CODE REVIEW

**Comment by denismerigoux** [comment]
I confirm you can remove the `duration / duration` operator.

**Comment by rmonat** [comment]
@denismerigoux I'm not sure to quite understand the error in the CI's test, could you take a look?

**Comment by denismerigoux** [comment]
In Catala when you declare a variable in a scope but provide no definition for it you get an error at execution time.

**Comment by rmonat** [comment]
I thought it was a test that was working in the main branch, not a new one here. Thank you!

**Comment by denismerigoux** [comment]
Can I merge?

**Comment by rmonat** [comment]
Yes (finally)!

**Comment by denismerigoux** [comment]
@TWal this PR's gonna break nix again. We need to add https://v3.ocaml.org/p/dates_calc/0.0.4 as a dependency.

**Pull request merged**
