### PR TITLE
Progress on Section 121

### PR DESCRIPTION
**Pull request by msprotz**
Currently blocked on #98 -- so sending this as a PR rather than a direct push on the repository. This could probably use another pair of legal eyes...?

### CODE REVIEW

**Review by ANDREISURKOV1987 — APPROVED** [review]

**Review by ANDREISURKOV1987 — APPROVED** [review]

**Review by ANDREISURKOV1987 — APPROVED** [review]

**Comment by denismerigoux** [comment]
@protz can I close this or you want to do something with it ?

**Comment by msprotz** [comment]
I think it'd be good to merge this. But I'm unclear why CI failed.

**Comment by denismerigoux** [comment]
I merged back `master` into this and updated the code such that it compiles but your additions cause the unit testing of Section 121 to fail, some scope arguments are not set it seems.

**Comment by denismerigoux** [comment]
Closing this because it's been stale for a very long time.

**Pull request closed without merging**
