### PR TITLE
Convert nix to flake (part 3)

### PR DESCRIPTION
**Pull request by lIlIlIlIIIIlIIIllIIlIllIIllIII**

### CODE REVIEW

**Comment by lIlIlIlIIIIlIIIllIIlIllIIllIII** [comment]
note that commits are now verified.

**Comment by lIlIlIlIIIIlIIIllIIlIllIIllIII** [comment]
https://github.com/CatalaLang/catala/runs/6753374974?check_suite_focus=true

**Comment by denismerigoux** [comment]
Still not working: https://github.com/CatalaLang/catala/runs/6757240249?check_suite_focus=true

**Comment by lIlIlIlIIIIlIIIllIIlIllIIllIII** [comment]
linked to https://github.com/CatalaLang/catala/commit/30297b27b87ba87ed8dc9ab10787bd1876a0ce6b

**Pull request merged**
