### PR TITLE
add support for duration multiplication

### LINKED ISSUE #269: Feature request: multiplication of durations
I would appreciate an operator that can multiply durations, such as `*^` with the English syntax (duration) *^ (integer). 

This has come up in attempts to formalize some Washington state laws. E.g., [RCW 46.61.5055(11)(b)](https://apps.leg.wa.gov/rcw/default.aspx?cite=46.61.5055): "For each violation of mandatory conditions of probation under (a)(i), (ii), (iii), (iv), or (v) of this subsection, the court shall order the convicted person to be confined for thirty days, which shall not be suspended or deferred." A duration multiplication operator would allow us to get the total confinement period, which is 30 days times the number of probation violations.

### PR DESCRIPTION
**Pull request by msprotz**
Nel and I worked on adding support for duration multiplication. This fixes #269.

Signed-off-by: Jonathan Protzenko <protz@microsoft.com>

### CODE REVIEW

**Comment by msprotz** [comment]
@denismerigoux do you know what the deal is with parser.messages? we struggled with that file, it seems auto-generated, and we had managed to reset it to a working state but now CI seems to break... thanks!

**Comment by AltGr** [comment]
`make parser-messages`, then committing the file into git should do the trick.
You can run `make check-promoted` to locally run the same check that the CI is running (I have that as a `pre-commit` hook to make sure I don't forget)

**Comment by AltGr** [comment]
(I did it for you — it seems that was the only thing missing! :tada: )

**Comment by denismerigoux** [comment]
@msprotz using `make build` instead of `dune build` runs all the rules concerning formatting and the auto-generation of this parser.messages files for you, I encourage you to use it. If you're curious about `parser.messages` it's the file that comes from menhir's error message enhancement feature described in http://cambium.inria.fr/~fpottier/publis/fpottier-reachability-cc2016.pdf.

**Review by denismerigoux — APPROVED** [review]
Thanks @msprotz and @kescher ! I added a few commits to complete the canonical checklist of operator addition:
* generalized the runtime implementation
* added Python runtime implementation
* added syntax on the sheat cheet

**Comment by msprotz** [comment]
Thanks Denis. I only run make build so I don't know what happened here. Thanks for fixing it!

**Pull request merged**
