### PR TITLE
Alternative logo and file icon

### PR DESCRIPTION
**Pull request by EmileRolley**
# Changelog

* New alternative logo in `svg` and `png`: 

logo_alt

* New alternative header `svg` and `png`:

logo-header_alt
 
* File icons for `catala_en`, `catala_fr` and `catala`:

Screenshot from 2021-04-06 11-51-46

### CODE REVIEW

**Comment by denismerigoux** [comment]
Thanks Émile! I really love the little file icons for IDEs. How did you manage to get them to display in your IDE ? Could you modify the syntax hilighting extensions for Atom and VSCode in `syntaw_highlighting` to enable them for everyone?

**Comment by EmileRolley** [comment]
> Thanks Émile! I really love the little file icons for IDEs. How did you manage to get them to display in your IDE ? Could you modify the syntax hilighting extensions for Atom and VSCode in `syntaw_highlighting` to enable them for everyone?

You're welcome! For now, I'm using [vscode-icons](https://github.com/vscode-icons/vscode-icons). The only way to modify VS Code syntax highlighting extensions is by adding an `iconTheme` contribution point in the *package.json* files, but only Catala files will be decorated... Consequently, I think that we should add icons by ourself or open a PR in order to submit the file icons to a VS Code icon theme extension..
I only looked at VS Code but maybe for other editors it's possible. I will check what can be done with Atom.

**Comment by denismerigoux** [comment]
> The only way to modify VS Code syntax highlighting extensions is by adding an iconTheme contribution point in the package.json files

Can't it be added here ? 

https://github.com/CatalaLang/catala/blob/7d05ee5d2a6d31e529e62352386ed1ce3525bccf/syntax_highlighting/en/vscode/package.json#L1-L25

**Comment by EmileRolley** [comment]
> > The only way to modify VS Code syntax highlighting extensions is by adding an iconTheme contribution point in the package.json files
> 
> Can't it be added here ?
> 
> https://github.com/CatalaLang/catala/blob/7d05ee5d2a6d31e529e62352386ed1ce3525bccf/syntax_highlighting/en/vscode/package.json#L1-L25

Yes, it can. But like I said, if we had it here we will need to choose for the new icon theme in VS Code which will contain only the icons for catala files. Moreover, if we want to separetes icons according catala syntaxes we won't be able to have them all in the same icon theme...

**Comment by EmileRolley** [comment]
I added a custom icon theme, but it's adding a lot of SVG files.. Maybe a separated repository could be made for `VS Code` extensions?

**Comment by denismerigoux** [comment]
Wouahou 10,000 files is a big number. I had not understood your first comment about the need to open a PR into an established extension, I think I understand now. Let's not clutter this repository with all these icon files, I think you can revert 72f2ba7 and I'll merge this PR the way it was before :)

**Comment by EmileRolley** [comment]
> Wouahou 10,000 files is a big number. I had not understood your first comment about the need to open a PR into an established extension, I think I understand now. Let's not clutter this repository with all these icon files, I think you can revert [72f2ba7](https://github.com/CatalaLang/catala/commit/72f2ba71e255d585cac7ddc56aa01476c07473d9) and I'll merge this PR the way it was before :)

It's done.

**Review by denismerigoux — APPROVED** [review]

**Pull request merged**
