### PR TITLE
Update opam dependencies

### PR DESCRIPTION
**Pull request by AltGr**
- The newer sedlex version allows us to remove a weird workaround (https://github.com/ocaml-community/sedlex/issues/12)
- dates_calc 0.0.6 is required (no dependency on `Str`) so we can remove specific pinning from the CI

This is stalled at the moment though because of Alpine 3.20 and Python stuff

### CODE REVIEW

**Comment by AltGr** [comment]
For CI to pass as is with Alpine 3.20 would require a musl 1.2 build to appear on this page: https://pypi.org/project/gmpy2/#files

**Comment by rprimet** [comment]
It might not be related to the musl version change, but rather to python 3.12? See https://github.com/aleaxit/gmpy/issues/446

**Comment by AltGr** [comment]
So, this *finally* all good, **but**
- newer alpine requires an additional texmf package for our docs builds, it's added here but not on the CI script on master (i.e. `Run integrated tests` should pass once merged)
- more annoying, the output of the test about backquotes seems to be dependent on the pandoc version we are using.
  image
  I see no good solution for now apart from disabling the test, @denismerigoux what do you think ?

**Comment by AltGr** [comment]
For me this is ready for merge, all issues have been resolved and CI should pass once merged. @vincent-botbol can you have a look before I merge ?

**Comment by vincent-botbol** [comment]
Looks good to me!

**Review by vincent-botbol — APPROVED** [review]

**Pull request merged**
